version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - config.env
    depends_on:
      - db
    command: >
      sh -c "
      while ! mysqladmin ping -h db --silent;
      do
        echo 'Waiting for the MySQL server to be ready...';
        sleep 2;
      done;
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fas_db
      MYSQL_USER: fas_user
      MYSQL_PASSWORD: fas_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
